    [buildPlans.iosevka-custom]
    family = "Iosevka Custom"
    spacing = "fixed"
    serifs = "sans"
    no-cv-ss = true
    export-glyph-names = false

    [buildPlans.iosevka-custom.variants.design]
    capital-g = "toothed-serifless-hooked"
    capital-j = "serifless"
    capital-q = "crossing"
    f = "flat-hook-serifless"
    r = "hookless-serifless"
    t = "flat-hook"
    two = "curly-neck"
    four = "closed"
    asterisk = "hex-low"
    paren = "flat-arc"
    brace = "curly"
    percent = "rings-continuous-slash"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"

    [buildPlans.iosevka-custom.slopes.upright]
    angle = 0
    shape = "upright"
    menu = "upright"
    css = "normal"
